services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-database
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-database
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-database
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-database
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-database
          property: password
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: TZ
        value: America/Sao_Paulo
      - key: N8N_DEFAULT_LOCALE
        value: br
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

databases:
  - name: n8n-database
    plan: free
